### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by CraftedCakes** [TheEssence/BugReports#12]
Multiple Bugs Within Prison
Bugs that I found while playing Op Prison

Username: 
CraftedCakes

The Issue: 
.There is a glitch with warps as I was able to access mines that i didn't have access too. For example I was rank Seaborgia and I was able to access the Ignition mines.

.You are able to take the armor off the armor stands at the block shop **PATCHED**

**Comment by FusionDeck** [comment]
- Armor stand bug *patched*
