### ISSUE TITLE
OP Prison Staff Ranking Issue

### ISSUE THREAD

**Issue by Psychotiix** [TheEssence/bugreports#7]
My Username:
Psychotix_YT

Issue
Staff Members are still able to go to any mine!

Steps to reproduce:
As you see i am currently Cobalt Rank!
https://gyazo.com/9c01e37e3e63d339394a288b26066708

All warp items are green, if this is how they are always going to be even when you dont have that rank, mind this.
https://gyazo.com/a8998de5b9f72fdb4b73a743f3df6b0d

As you see i am in Ignition Mine!
https://gyazo.com/f36710ba7db91d7c8b023120086b2a47
What we (as developers) can do to reproduce the bug.

Hope this issue can still be fixed!

(These are normal mines, the donor mines for staff members don't work, so the donor mines are all good)

**Comment by FusionDeck** [comment]
The issue has been fixed, if it has actually NOT been patched, please post a new issue linking it to this.
