### ISSUE TITLE
OP Prison Plot Issue

### ISSUE THREAD

**Issue by Psychotiix** [TheEssence/bugreports#8]
Your Username: Psychotix_YT

The Issue: Players cannot break/place blocks in plots

Steps to reproduce: Try and break plot blocks, im not sure what ranks are able to break blocks in the plots, but mods cant, so i don't think Members can either

Miscellaneous information:

When i try and break blocks in plots:
https://gyazo.com/e601393a6cae56c83e1174e53e289329

When i try and place blocks in plots:
https://gyazo.com/5f744b16d13ffbfec75aceecfce5824d

**Comment by FusionDeck** [comment]
The issue has been patched.
